### ISSUE TITLE
when email verifier

### ISSUE THREAD

**Issue by Minhe173** [Imagine-YT/Roblox-Account-Generator#1]

**Comment by Imagine-YT** [comment]
As of now Email Verifier is a bit far away from the next updates, but new features are going to be added and some bugs will be fixed in the next update which I'm releasing in about 15 minutes!
My best guess for Email Verifier is either next update or the update next to it, in short --> it can take up to 2 weeks (depending on if I can make one)
I'm sorry for any inconvenience (if there is any)

**Comment by Minhe173** [comment]
whats the email api u using?

**Comment by Imagine-YT** [comment]
I have yet not started working on email part of then generator.

**Comment by TheBlackCookie** [comment]
> whats the email api u using?

Mail.tm has an alright free email API with an alright rate limit
